kind: pipeline
name: default
steps:
  - name: setup
    image: node:8
    when:
      event: [push, pull_request]
    commands:
      - yarn
  - name: test
    image: node:8
    when:
      event: [push, pull_request]
    group: testing
    commands:
      - yarn test
  - name: lint
    image: node:8
    when:
      event: [push, pull_request]
    group: testing
    commands:
      - yarn lint
  - name: flow
    image: node:8
    when:
      event: [push, pull_request]
    group: testing
    commands:
      - yarn flow --quiet
  - name: build
    image: node:8
    when:
      event: [push, pull_request]
      branch:
        exclude: [prod]
    group: testing
    commands:
      - yarn build
